// <auto-generated />
namespace TrashCollector.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class updatedmodelpickupsagainagain : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updatedmodelpickupsagainagain));
        
        string IMigrationMetadata.Id
        {
            get { return "201811020106186_updated model pickups again again"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
